### ISSUE TITLE
Uncaught TypeError: Cannot destructure property 'asJsonSym' of 'symbols' as it is undefined.

### ISSUE THREAD

**Issue by naivefun** [pinojs/pino-caller#127]
```
Uncaught TypeError: Cannot destructure property 'asJsonSym' of 'symbols' as it is undefined.
```

<img width="379" alt="image" src="https://user-images.githubusercontent.com/10683378/221712761-c42792fa-0b12-4218-b3f9-2932a91508ff.png">

- pino: latest:8.x.x
- caller: latest

Is it not available for browser?

**Comment by mcollina** [comment]
Unfortunately no.
