### ISSUE TITLE
Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by tuananh** [pinojs/pino-caller#22]
I tried to log some info and this is what i get in the terminal. using latest version of `pino-caller` and pino v5

```js
logger.info({name: 'myError', payload: { hello: 'world' } } )
```
```
   TypeError: Cannot read property 'substr' of undefined
       at Proxy.asJson (D:\Code\myapp\node_modules\pino-caller\index.js:17:149)
       at Proxy.write (D:\Code\myapp\node_modules\pino\lib\proto.js:148:28)       at Proxy.LOG (D:\Code\myapp\node_modules\pino\lib\tools.js:38:21)   
       at Object.handler (D:\Code\myapp\routes\token.js:39:28) +128ms 
```

**Comment by phra** [comment]
@tuananh can you share a minimal repro code? thanks.

**Comment by tuananh** [comment]
i tried to extract from my project but it works in the repro. weird.

lemme figure out what i did in my project that's unique to cause this bug.

**Comment by phra** [comment]
i will close the issue for now, feel free to reopen it if you have news.

**Comment by moltar** [comment]
I'm having the same issue.

@tuananh are you getting this inside jest tests by any chance?

**Comment by tuananh** [comment]
> I'm having the same issue.
> 
> @tuananh are you getting this inside jest tests by any chance?

no, it was inside a fastify plugin.
