### ISSUE TITLE
FR: an option to output relative path

### ISSUE THREAD

**Issue by freopen** [pinojs/pino-caller#29]
Would be cool to be able to output only the part of path relative to project root.

Currently my logs look like that: 

```
INFO [14:27:18] <Server.<anonymous> (/home/freopen/projects/<project_name>/src/server/index.ts:28:40)>: 🚀 Server ready at http://localhost:4000/graphql
```

Would be much more readable for me to see something like that:

```
INFO [14:27:18] <Server.<anonymous> (src/server/index.ts:28:40)>: 🚀 Server ready at http://localhost:4000/graphql
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by phra** [comment]
cool idea!

**Comment by mcollina** [comment]
Actually that would have been nice
