### ISSUE TITLE
Adding TypeScript types as @types/pino-caller 

### ISSUE THREAD

**Issue by halostatue** [pinojs/pino-caller#56]
I’m considering switching to TypeScript for a project, and this is a project which has no TS type declarations available, so I have added it to DefinitelyTyped. I _believe_ that what I have is correct, but if you have any opinions on this, it would be useful.

DefinitelyTyped/DefinitelyTyped#56120

**Comment by kibertoad** [comment]
Would you consider submitting types to project directly instead?

**Comment by halostatue** [comment]
I barely know what I’m doing with this stuff, but you’re free to pull the type definitions ([types/pino-caller/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/46f4efbb3167b0bf2ea5a25e686656e935405b0d/types/pino-caller/index.d.ts)) and save it as `index.d.ts` and add `"types": "index.d.ts"` to your `package.json`.

I _think_ that’s all that is needed. If that’s done and a new version is released (so we can import the types from that version), I am happy to close the PR.

The thing I _don’t_ know is how the `import Pino = require("pino")` will work in this scenario.

**Comment by halostatue** [comment]
The DirectlyTyped repo had a lot of tooling that helped me build that type set with tests; the good news is that they work—they silence the warnings and errors on my project and do not seem to introduce any new ones. They also _strongly_ recommend that packages deliver their own types.

**Comment by peterblazejewicz** [comment]
@halostatue 
there is a convention already in TypeScript automatic types resolution that follows conventions from `pacage.json`. Please make PR here with your DT file placing directly along the `index.js`. It should be just added to published content to NPM registry, here is more on this:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package

thanks!

**Comment by halostatue** [comment]
Resolved with #57

**Comment by kibertoad** [comment]
Released in 3.2.0
