### ISSUE TITLE
change level

### ISSUE THREAD

**Issue by xenoterracide** [pinojs/pino-caller#90]
we obnoxiously have our own wrapper, which means that all logs come from the same file, could you implement some kind of stack adjustment or files exclusion?

this is kind of useless
```js
    caller: "Logger.debug (/Users/me/IdeaProjects/MyProj/node_modules/@Wrappers/logger/lib/index.js:215:14)"
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by jmealo** [comment]
@xenoterracide: would you want to have this configuration driven?

**Comment by jmealo** [comment]
@xenoterracide: You can use a custom Pino serializer for the `caller` object to do any kind of rewriting that you need to do. I don't know if it makes sense to make any changes here.

```javascript
const pinoOptions = {
   level: 'info',
   serializers: {
      caller: (caller) => caller.startsWith('Logger.debug') && caller.indexOf('@Wrappers') !== -1) ? undefined: caller
   }
}
```

I believe if you return `undefined` from a serializer that it'll be excluded from the JSON output. That should remove the `caller` property (IIRC) entirely (or allow you to rewrite it).

**Comment by g-gundam** [comment]
@mcollina You can probably close this issue now.  @xenoterracide's original problem should be solved.
